
# Choose Algorithm
algorithm: SayPlan  # Inter-LLM, MoMa-LLM, SayPlan

# Procthor Scene ID 
scene_id: 1

# LLM Configurations
llm_model: gpt-5-mini  # gpt-5-nano
temperature: 0.0   # 0.0 for deterministic, 1.0 for more random
OPENAI_API_KEY: <Your Own Key>

# Task Definition
task: multi_object_collection



